Repository mimiframework/Mimi.jl, pull requests merged in 2018-08, with the labels that each got.

#280 Minor cleanup to close a few issues
  src/core/model.jl
  src/core/time.jl
  src/explorer/buildspecs.jl
  src/mcs/EmpiricalDistribution.jl
  src/mcs/montecarlo.jl
  src/utils/getdataframe.jl
  test/mcs/test_defmcs.jl
  test/test_explorer.jl
  test/test_getdataframe.jl
Labels: enhancement

#296 API-docs
  src/Mimi.jl
  src/components/adder.jl
  src/core/build.jl
  src/core/connections.jl
  src/core/defcomp.jl
  src/core/defs.jl
  src/core/instances.jl
  src/core/model.jl
  src/core/references.jl
  src/core/time.jl
  src/core/types.jl
  src/explorer/explore.jl
  src/mcs/mcs_types.jl
  src/mcs/montecarlo.jl
  src/utils/getdataframe.jl
  src/utils/misc.jl
  src/utils/plotting.jl
  test/test_explorer.jl
Labels: documentation

#295 Revised treatment of default parameter values and parameter types.
  src/core/defcomp.jl
  src/core/defs.jl
  test/test_parametertypes.jl
Labels: bug

#303 WIP Improve Code Coverage
  src/core/time.jl
  test/runtests.jl
  test/test_adder.jl
  test/test_clock.jl
  test/test_components.jl
  test/test_components_ordering.jl
  test/test_connectorcomp.jl
  test/test_dimensions.jl
  test/test_explorer.jl
  test/test_getdataframe.jl
  test/test_getindex.jl
  test/test_getindex_variabletimestep.jl
  test/test_main.jl
  test/test_main_variabletimestep.jl
  test/test_marginal_models.jl
  test/test_metainfo.jl
  test/test_metainfo_variabletimestep.jl
  test/test_model_structure.jl
  test/test_model_structure_variabletimestep.jl
  test/test_mult_getdataframe.jl
  test/test_num_components.jl
  test/test_parameter_labels.jl
  test/test_parametertypes.jl
  test/test_timesteparrays.jl
  test/test_timesteps.jl
  test/test_tools.jl
  test/test_units.jl
  test/test_variables_model_instance.jl
Labels: enhancement

#302 Update comp_defs when redefining time dimension
  src/core/connections.jl
  src/core/defs.jl
  test/test_dimensions.jl
Labels: bug
